name: Deploy Service to EB

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      service_path:
        required: true
        type: string
      application_name:
        required: true
        type: string
      environment_name:
        required: true
        type: string
      aws_region:
        required: false
        type: string
        default: ap-southeast-1
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate deployment package
        working-directory: ${{ inputs.service_path }}
        run: zip -r $GITHUB_WORKSPACE/deploy.zip . -x '*.git*' -x 'target/*' -x '.env'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ inputs.application_name }}
          environment_name: ${{ inputs.environment_name }}
          version_label: ${{ inputs.service_name }}-v${{ github.run_number }}
          region: ${{ inputs.aws_region }}
          deployment_package: deploy.zip
