name: Deploy Collab Service
on:
  push:
    branches:
      - master
    paths:
      - "backend-services/collab-backend-service/**"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-service-to-eb.yml
    with:
      service_name: collab-service
      service_path: backend-services/collab-backend-service
      application_name: peerprep-collab-service
      environment_name: peerprep-collab-service-prod
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
