name: Deploy collab-ui-service to S3

on:
  push:
    branches:
      - master
    paths:
      - "ui-services/collab-ui-service/**"
      - ".github/workflows/deploy-collab-ui.yml"
  workflow_dispatch:

jobs:
  call-base:
    uses: ./.github/workflows/deploy-ui-to-s3.yml
    with:
      name: collab-ui-service
      path: ui-services/collab-ui-service
      bucket: peerprep-collab-ui-service
    secrets: inherit
